# Generated by Django 4.2.2 on 2023-07-05 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='NULL', max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('idCategoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.categoria')),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0)),
                ('productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
