# Generated by Django 4.2.2 on 2023-07-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.categoria'),
        ),
    ]
